spring.application.name=bff

usuario.url=http://localhost:8080/usuario
agendadortarefas.url=http://localhost:8081/tarefa
notificacao.url=http://localhost:8082/email

server.port=8083

cron.horario=*/10 * * * * *

usuario.email=admin@admin.com
usuario.senha=1234